Category.create(title: 'Little Cacti')
category = Category.all.first
category.items.create(title: 'Pink Cactus', description: "It has a little flower on top", price: 10.95, image: File.new("#{Rails.root}/app/assets/images/2.jpg"))
category.items.create(title: 'Pretty Cactus', description: 'It comes in a geometric glass pot.', price: 20.95, image: File.new("#{Rails.root}/app/assets/images/1.jpg"))
category.items.create(title: 'Basic Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'Basic white girl Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'stuff Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'whatever Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'cool Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'cooler Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'coolest Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'Basic periwinikle', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'tom Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'django Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'sweaters Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'picket fence Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'jcrew Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'frappacuino Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'pumpkin spice Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'll bean Cactus', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'Basic palm frond', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'consider', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'the', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'coconut', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'moana', description: 'It comes in a ceramic pot.', price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
category.items.create(title: 'super long tite', description: 'It  in a ceramic pot.It  in a ceramic pot.It  in a ceramic pot.It in a ceramic pot.
It in a ceramic pot.It in a ceramic pot.It in a ceramic pot.It in a ceramic pot.It in a ceramic pot.It in a ceramic pot.It in a ceramic pot.
It in a ceramic pot.It in a ceramic pot.It in a ceramic pot.It  in a ceramic pot.It  in a ceramic pot.It  in a ceramic pot.It  in a ceramic pot.',
price: 6.95, image: File.new("#{Rails.root}/app/assets/images/3.jpg"))
